[project]
name = "spider-agent-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate",
    "chromadb",
    "dashscope>=1.23.4",
    "db-dtypes>=1.4.3",
    "diskcache",
    "docker",
    "duckdb",
    "flaml",
    "fuzzywuzzy",
    "gdown>=5.2.0",
    "google-cloud-bigquery",
    "google-generativeai",
    "groq>=0.26.0",
    "gymnasium",
    "langchain",
    "llama-cpp-python",
    "matplotlib>=3.10.3",
    "minify-html",
    "mysql-connector-python",
    "numpy>=2.2.6",
    "openai==1.31.0",
    "openpyxl>=3.1.5",
    "optimum",
    "pandas",
    "playwright",
    "plotly",
    "psycopg2-binary",
    "pyarrow>=20.0.0",
    "pypdf",
    "python-levenshtein",
    "rich",
    "rpyc",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
    "snowflake-connector-python>=3.15.0",
    "statsmodels>=0.14.4",
    "tabulate>=0.9.0",
    "tenacity",
    "tiktoken",
    "torch>=2.7.1",
    "transformers",
    "unstructured",
    "xgboost>=3.0.2",
]
